### ISSUE TITLE
bug: Vscode extension uses so much resources

### ISSUE THREAD

**Issue by ikemHood** [starkware-libs/cairo#6509] opened 2024-10-23 10:31 UTC
# Bug Report

**Cairo version:**

scarb 2.8.3 (54938ce3b 2024-09-26)
cairo: 2.8.2 (https://crates.io/crates/cairo-lang-compiler/2.8.2)
sierra: 1.6.0

**Current behavior:**

keeps running `scarb is resolving project`

I am using Cairo  1.0 vscode extension for syntax highligh, I have over time figured that it uses too much resources and makes my device to get sluggish over time

my system spec:
OS: Fedora workstation 40
 Processor: intel i7 11th gen, 
memory:  16GB ram. 

I suspect the  `scarb is resolving project` notice that displays on vscode is running a process that gets duplicated to infinity

**Expected behavior:**

Should provide syntax highligh without using up too many resources

**Steps to reproduce:**

not sure, but just Intsalling and enabling  the extension. 
I have encountered this on windows, wsl and now fedora

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Comment by mkaput** [comment] 2024-10-23 10:36
duplicate of #5047. we have also drastically improved resources usage in #6508 so Cairo 2.9 will be a great improvement

**Closed by mkaput** 2024-10-23 10:36 UTC
Labels: bug
