### ISSUE TITLE
feat: allow importing a function with the same name as the module/crate in which it exists

### ISSUE THREAD

**Issue by misicnenad** [starkware-libs/cairo#5957] opened 2024-07-04 06:44 UTC
# Feature Request

**Describe the Feature Request**

I would like to be able to import functions that have the same name as their parent modules.

Currently if I have a module `mod sublist` which has a nested function with the same name `fn sublist`, everything is fine. But if I try to import said function into another module like `use sublist::sublist`, the compiler complains that `"The name `sublist` is defined multiple times."`.

The same issue occurs if the function is nested inside yet another module, that is already nested inside the module with the same name as the function, e.g.:
```rust
mod sublist {
  pub mod nested {
    pub fn sublist() {}
  }
}

use sublist::nested::sublist; // fails!

fn main() {
  sublist();
}
```
The same issue occurs if the function is nested inside a completely unrelated module, but has the same name as another module, e.g.:
```rust
mod sublist {
  pub fn some_func() {}
}

mod unrelated {
  pub fn sublist() {}
}

use unrelated::sublist; // fails! The name `sublist` is defined multiple times.

fn main() {
  sublist();
}
```

**Describe Preferred Solution**

I would like to be able to import functions that have the same name as parent modules:
```rust
use sublist::sublist; 
// OR
use sublist::nested::sublist;
// OR
use unrelated::sublist;
```

**Describe Alternatives**

To get around this, I give name aliases to imports:
```rust
use sublist::sublist as sb; // works
use sublist::nested::sublist as nested_sublist; // works
use unrelated::sublist as unrelated_sublist; // works
```

**Related Code**

```rust
mod sublist {
    pub fn sublist() {
      println!("sublist");
    }

    pub mod nested {
        pub fn sublist() {
            println!("nested sublist");
        }
    }
}

mod unrelated {
    pub fn sublist() {
        println!("unrelated sublist");
    }
}

// THIS IS WHAT I'D LIKE TO BE ABLE TO DO
use sublist::sublist;
// OR
use sublist::nested::sublist;
// OR
use unrelated::sublist;

fn main() {
    sublist();
}
```

**Additional Context**

Rust allows for conflicting names between module and function names:
https://stackoverflow.com/questions/43358940/why-does-a-module-with-a-submodule-and-a-function-with-conflicting-names-work

Sometimes this can be useful.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [x] No

**Comment by orizi** [comment] 2024-07-04 13:00
did you have a specific case you needed it?
or is it just "sometime useful"?

if not - rather no allow for the confusion this can cause - especially since it is logical not to allow two items with the same name at the same context.

**Comment by misicnenad** [comment] 2024-07-04 14:04
I'd categorize is as "sometimes useful".

I'm creating a Cairo track on Exercism, and one of the exercise I need to implement is called ["sublist"](https://github.com/exercism/problem-specifications/blob/main/exercises/sublist/description.md); the task is to implement a function that can check whether a list is a sublist of another list (for Cairo, instead of "lists" I'm using "arrays").

So the module name must match the exercise name, which is `sublist`, and I wanted to name the function `fn sublist` as well, as implementing is the whole point of the exercise/module.

That's how I stumbled upon this limitation of Cairo, so wanted to raise an issue in case you guys find it worth implementing.

**Comment by orizi** [comment] 2024-07-04 15:27
honestly - it still seems to me more confusing than not - especially if we add `pub` into the mix:
if i use it outside - which item did we import - i see this too works in rust, which i still find more confusing than not.

**Comment by misicnenad** [comment] 2024-07-10 11:09
@orizi as this was more of a "nice to have" feature request, I'll leave it to you and the team to decide whether you think this is worth implementing and whether it aligns with your idea of what Cairo is supposed to be.
If you decide that this is "out of scope", let me know and I'll close the issue.

**Comment by orizi** [comment] 2024-07-11 10:07
I think it is "out of scope" for now. will reopen if becomes relevant.

**Closed by orizi** 2024-07-11 10:07 UTC
Labels: enhancement

**Comment by misicnenad** [comment] 2024-07-22 07:58
@orizi writing a thought here for future reference - being able to define a function/method/whatever with the same name as the module/crate, but then _not_ being able to import it in another file using that same name is very counter-intuitive.
I would rather prefer either to:
1. Be able to define an item with the same name as the module/crate and _be able to import it with the same name_ (as described in the issue description).
-OR-
2. Not be able to define an item with the same name as the module/crate at all.

Having either 1) _or_ 2) keeps things consistent. Having a weird mix of the two is... weird.

**Comment by misicnenad** [comment] 2024-07-22 08:19
Hmm, why doesn't this work then?
```rust
mod a {
  pub mod b {
    pub type a = u64;
  }
}
use a::b::a; // The name `a` is defined multiple times.
```

**Comment by orizi** [comment] 2024-07-22 08:27
exact same reason - the issue is having the same name in the same context twice. In this example it is `a` in the outer context.

**Comment by misicnenad** [comment] 2024-07-22 08:45
I don't really understand how `type a` is "the same name in the same context twice", but `type b` in your original example is not.

**Comment by orizi** [comment] 2024-07-22 08:49
```
// context has name `a` (the module) and (`b` the `use`).
mod a {
  // context has only name `b`.
  mod b {
    // context has only name `b`.
    type b = u64;
  }
}
use a::b::b;
```

vs.

```
// context has name `a` twice (first the module, then the `use`).
mod a {
  // context has only name `b`.
  mod b {
    // context has only name `a`.
    type a = u64;
  }
}
use a::b::a;
```

**Comment by misicnenad** [comment] 2024-07-22 09:13
I understand now where my confusion was coming from.
Thanks!
