### ISSUE TITLE
bug: LSP completion dialog should only recommend public members of a module

### ISSUE THREAD

**Issue by 0xNeshi** [starkware-libs/cairo#5660] opened 2024-05-28 06:26 UTC
# Bug Report

**Cairo version:**
2.6.3

**Current behavior:**

When defining a module with some public members and trying to import said members, a completion dialog appears, but the language server includes non-public members in the dialog. Additionally, the lang. server includes non-members in the dialog (in this case `ShapeGeometry`).

Example below:
![image](https://github.com/starkware-libs/cairo/assets/19427053/67bb0075-165f-47f7-90ff-c46fc8f145a9)

Trying to import non-public members (and non-members) results in an error of course:
![image](https://github.com/starkware-libs/cairo/assets/19427053/4e64d293-4858-425e-a85e-ec07c7fee3be)
![image](https://github.com/starkware-libs/cairo/assets/19427053/63593ee1-e800-4a56-9501-23a8a6f5d213)
![image](https://github.com/starkware-libs/cairo/assets/19427053/ef3d4cce-51d3-4a5a-a37a-af9b9e9e9d9c)

Importing a public member works as expected:
![image](https://github.com/starkware-libs/cairo/assets/19427053/92c331da-e67a-4284-8467-7097907bef15)

**Expected behavior:**

The completion dialog should only include actual module *members* and only _those that can actually be imported_.

**Steps to reproduce:**

- create a new Scarb package
- open `lib.cairo` in VS Code (ensure Cairo 1.0 extension is installed)
- paste the code from "Related code" section below into the opened file
- put the cursor at the end of the incomplete `use circle::` statement
- prompt the completion dialog to open (usually `CTRL + Space`)

**Related code:**

```rust
trait ShapeGeometry<T> {
    fn boundary(self: T) -> u64;
}

mod circle {
    use super::ShapeGeometry;

    #[derive(Drop)]
    pub struct Circle {
        pub radius: u64,
    }

    impl CircleGeometry of ShapeGeometry<Circle> {
        fn boundary(self: Circle) -> u64 {
            (2 * 314 * self.radius) / 100
        }
    }
}

use circle::
```

**Other information:**

Related issue: https://github.com/starkware-libs/cairo/issues/5664

**Comment by Utilitycoder** [comment] 2024-05-28 11:08
Hi, I would love to work on this. I however need pointers to where this should be fixed.

**Comment by mkaput** [comment] 2024-05-28 11:18
Task is yours. Thanks ♥️ 

The entry point for completion logic is here:

https://github.com/starkware-libs/cairo/blob/c6d602981962f759ff66c81ecfb75e2e24c66d66/crates/cairo-lang-language-server/src/ide/completion/mod.rs#L19-L59

This looks to be `::`-completion, which is computed here:

https://github.com/starkware-libs/cairo/blob/c6d602981962f759ff66c81ecfb75e2e24c66d66/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L115-L188

As you can see, this is basically just a banch of ifs for various AST items.

I guess you simply have to put appropriate filters here:

https://github.com/starkware-libs/cairo/blob/c6d602981962f759ff66c81ecfb75e2e24c66d66/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L137-L148

---

BTW It would be awesome if you'd also contribute completion E2E tests, as you're touching this. There are none yet, but they should be pretty similar to hover test for example:

https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-language-server/tests/e2e/hover.rs
https://github.com/starkware-libs/cairo/tree/main/crates/cairo-lang-language-server/tests/test_data/hover

Would you like to make this part? I don't want to enforce this on you. 😃

**Comment by mkaput** [comment] 2024-06-17 09:12
@Utilitycoder hey, how's it going? Would you like some assistance from my side in this area?

**Comment by Utilitycoder** [comment] 2024-06-21 23:06
@mkaput I have been sick but slowly getting back to optimum health. I will take a look and let you know If I'd be able to proceed with it.

**Comment by piotmag769** [comment] 2024-08-01 13:41
I think it is done (at least partially) after #6060 and #6091, no? We may just want to review if the logic of using public items only is needed somewhere else @mkaput @gilbens-starkware

**Comment by mkaput** [comment] 2024-08-01 16:53
> I think it is done (at least partially) after #6060 and #6091, no? We may just want to review if the logic of using public items only is needed somewhere else @mkaput @gilbens-starkware

I didn't verify what you said, but I doubt so: Gil's work is adding auto-imports for stuff that is `pub` still. The problem is that LS is also suggesting things that are not `pub` at all.

For example, in the screenshot from the issue description, `ShapeGeometry` should never be suggested because it's not `pub use`.

**Comment by piotmag769** [comment] 2024-08-01 18:20
Okay, so it is basically about fixing dot completions then

**Comment by gilbens-starkware** [comment] 2024-08-04 07:58
Indeed it is not fixed.
However, a good entry point now will be to look at [visible_traits_from_module](https://github.com/starkware-libs/cairo/blob/d6e107fc0d30affa3262ad5e2c825d372d6b8fd3/crates/cairo-lang-semantic/src/lsp_helpers.rs#L202), this issue will need something similar e.g. `visible_items_from_issue`.

**Closed** 2024-11-14 18:26 UTC
Labels: bug, good first issue, help wanted, ide
