### ISSUE TITLE
bug: Variable was previously moved error when returning from a loop

### ISSUE THREAD

**Issue by milancermak** [starkware-libs/cairo#3049] opened 2023-05-05 20:49 UTC
# Bug Report

**Cairo version:** 8a2d3842

**Current behavior:**

Consider the following code:

```rust
use array::ArrayTrait;

#[derive(Copy, Drop, Serde)]
struct u250 {
    inner: felt252
}

fn doo(mut c: felt252) -> Array<u250> {
    let mut res = ArrayTrait::<u250>::new();

    loop {
        if c == 0 {
            break ();
        }

        res.append(u250 { inner: c });
        c -= 1;
    };

    res
}

#[test]
#[available_gas(100000000)]
fn test_arr_custom_type() {
    let a = doo(10);
    assert(a.len() == 10, 'a len');
}
```

This all works fine. The problem arises when I modify the `doo` fn slightly to return directly from the loop:

```rust
fn doo(mut c: felt252) -> Array<u250> {
    let mut res = ArrayTrait::<u250>::new();

    loop {
        if c == 0 {
            break res;
        }

        res.append(u250 { inner: c });
        c -= 1;
    }
}
```

When trying to run the test, I get a compiler error:

```sh
error: Variable was previously moved. Trait has no implementation in context: core::traits::Copy::<core::array::Array::<new_type::new_type::u250>>
 --> new_type.cairo:16:9
        res.append(u250 { inner: c });
        ^*^

Error: failed to compile: ./contracts/new_type.cairo
```

**Expected behavior:**

I would expect the code to compile and function the same way as when returning from outside the loop.

**Comment by spapinistarkware** [comment] 2023-05-08 06:06
Duplicate of https://github.com/starkware-libs/cairo/issues/2816

**Closed by spapinistarkware** 2023-05-08 06:06 UTC
Labels: bug
