### ISSUE TITLE
bug: serialization causes felt to give 'Unknown ap change'

### ISSUE THREAD

**Issue by microbecode** [starkware-libs/cairo#3237] opened 2023-05-24 11:43 UTC
# Bug Report

**Cairo version:**

scarb 0.2.0 (ba49ae913 2023-05-17)
cairo: 1.0.0 (https://crates.io/crates/cairo-lang-compiler/1.0.0)
cairo-lang-test-runner 1.1.0-alpha0

**Current behavior:**

Running a specific unit test fails with 
```
Error: Failed setting up runner.

Caused by:
    #2525->#2526: Got 'Unknown ap change' error while moving [22].
```

**Expected behavior:**

Test should work

**Steps to reproduce:**

1. Run unit test from https://github.com/eqlabs/starknet-multisig/blob/3a4f60c994dbf1da67d890ed39b543e8476e4fc8/src/tests/temp.cairo with scarb or cairo-test

Here's the full unit test code, just in case:
 ```
#[test]
 #[available_gas(2000000)]
 fn test_temp() {
    let mut myarr = ArrayTrait::<felt252>::new(); 
    let myvar = 123_felt252;
    myarr.append(myvar);
    let mut serializedArr = ArrayTrait::<felt252>::new(); 
    myarr.serialize(ref serializedArr);
    let incu32 = u32_try_from_felt252(myvar);
 }
```

**Other information:**

The error goes away if I remove the serialization, or remove the last type cast.

**Comment by orizi** [comment] 2023-05-28 12:06
This was solved by making the `dup` libfunc accept `const` as its input - but this is currently only at the `sierra-v1.1.0` branch, as this would make the compiler create sierra code that would not be accepted by starknet (as it is currently expects `dup` to only work on fully stored values).
currently the issue is the constants so you can:
- Work over `sierra-v1.1.0`.
- Define consts out of the function.
- Restate the constant.

This should be merged into main before the next release.

**Comment by wraitii** [comment] 2023-09-08 13:22
@orizi I believe this is solved then and should be closed ? (found it while looking for an `ap change` error)

**Closed** 2023-09-08 15:22 UTC
Labels: bug
