### ISSUE TITLE
feat: use folder without creating a file

### ISSUE THREAD

**Issue by gaetbout** [starkware-libs/cairo#3496] opened 2023-06-25 10:03 UTC
# Feature Request

At the moment, when creating a subfolder you need to create a cairo file that'll containing all the stuff existing in that folder:
 - lib.cairo
 - tests (folder)
 - tests.cairo

So if I have a tests folder I'll need to have a tests.cairo file that'll contain one line per fail existing in tests.
It would be easier if it was possible to make those directly in lib.cairo:
```rust
mod tests;
use tests:test_file1;
use tests:test_file2;
```

**Comment by mkaput** [comment] 2023-06-26 08:01
Mind that this is diverging from Rust's design. Perhaps this could be replaced with a compiler plugin like https://github.com/dtolnay/automod

**Comment by gaetbout** [comment] 2023-06-26 09:26
Not sure I understand how it differs:
https://doc.rust-lang.org/cargo/guide/project-layout.html
Keen to understand what I'm missing 😄

**Comment by mkaput** [comment] 2023-06-26 09:41
Your suggestion is missing module declarations for `test_file1` etc. and I understand that you ask for having an ability to omit them. That's not how things work in both Cairo and Rust, these `mod test_file1;` items are the only ways to tell the compiler about the existence of these modules (in normal module tree). The `automod` procmacro allows you to autogenerate these.

In Rust there is an UX trick that makes the `tests` folder work differently, but mind that this is just an UX trick, and implementation-wise this works completely different. Each file in `tests` folder is actually a separate compilation unit and is processed on Cargo-level. The outcome of this is that you get separate test binaries for each top-level file in `tests` dir in Rust. This is not something portable to Cairo and still it's a topic for the test runner to handle.

**Comment by milancermak** [comment] 2023-06-27 09:59
I think what @gaetbout has it mind (and please correct me if I misunderstood) is not just the `tests` dir specifically but that any "module directory" has to have a .cairo file of the same name associated with it.

Here's a different example:

```sh
src
├── core
│   ├── bar.cairo
│   ├── baz.cairo
│   ├── foo.cairo
├── core.cairo
├── external
│   └── pragma.cairo
├── external.cairo
├── interfaces
│   ├── IBar.cairo
│   ├── IBaz.cairo
│   ├── IFoo.cairo
│   └── external.cairo
├── interfaces.cairo
└── lib.cairo
```

Where e.g. `core.cairo` is only:

```rust
mod bar;
mod baz;
mod foo;
```

and `lib.cairo` is:
```rust
mod core;
mod external;
mod interfaces;
```

The question is why do we need `core.cairo`, `external.cairo` and `interfaces.cairo` at all if they only declare the `mod`s in the respective directories. Can't the compiler figure out by itself from `lib.cairo`?

**Comment by mkaput** [comment] 2023-06-27 13:33
I think it's obvious that the compiler could figure this right now, but how should it behave when #3457 is merged? Should all modules be `pub` or not?

**Comment by milancermak** [comment] 2023-06-27 15:54
They should be whatever they're declared as. 

If I understand the linked PR correctly, there will be the possibility to have `pub mod Foo` and also an internal `mod Bar`.

**Comment by mkaput** [comment] 2023-06-27 16:49
I was asking about these compiler inferred declarations for files within a directory :-) In your example, that would mean, what should the compiler infer as contents of `core.cairo` and `lib.cairo` files

**Comment by gaetbout** [comment] 2023-09-08 13:23
@milancermak 

This can be solved following this pattern:

mod interfaces {
    mod IBar;
    mod IBaz;
    mod IFoo;
}

**Closed** 2023-09-08 13:24 UTC
Labels: enhancement

**Comment by milancermak** [comment] 2023-09-12 10:02
Since Twitter is not the best place to discuss things, moving [the discussion](https://twitter.com/milancermak/status/1701235152980983937) here.

The question is, can we use mod declaration without intermediate files, as described above?

@mkaput considers this to be an unintended compiler bug, @gaetbout an undocumented feature. I think it's pretty neat as well. In either case, it's used in [Satoru](https://github.com/keep-starknet-strange/satoru/blob/main/src/lib.cairo)

What do you think @OriStarkware @spapinistarkware @yuvalsw? Does this work as intended? Can we keep using it?

**Comment by tekkac** [comment] 2023-09-14 12:46
Seems we already can do it, I've seen it used in multiple other projects.

It seems like a feature in the [Rust grammar](https://doc.rust-lang.org/reference/items/modules.html) so I see no reason to remove it.
